first commit
IlyaOsipenkov/go-db-sql-final pull request #1
Opened 2024-10-16 20:18 UTC by IlyaOsipenkov

Добрый вечер, задание ещё недоделал

2024-10-16 21:40 UTC, just-musha commented
@IlyaOsipenkov привет! Без проблем, присылай как будет готово. Жду

2024-11-07 16:24 UTC, IlyaOsipenkov commented
Дорый вечер, прошу проверить мое задание

2024-11-08 08:08 UTC, just-musha requested changes
Привет! Хорошая работа, видно что получилось разобраться в материале. Из правок - проверка ошибки (см коммент) и assert вместо require, где это имеет смысл, и ещё возврат пустой структуры Остальное на твое усмотрение. Удачи!

2024-11-08 08:08 UTC, just-musha commented on parcel_test.go
> +		require.Equal(t, parcelMap[parcel.Number].Client, parcel.Client)
Тут лучше использовать assert - чтобы тест не завершался при первом не совпадении, и мы увидели сразу их все

2024-11-08 08:08 UTC, just-musha commented on main.go
> +//test
Это нужное?

2024-11-08 08:08 UTC, just-musha commented on parcel.go
> +type ParcelStore interface {
Хорошее решение с интерфейсом!

2024-11-08 08:08 UTC, just-musha commented on parcel.go
> +	}
После цикла - не забыть проверить `rows.Err`

2024-11-08 08:08 UTC, just-musha commented on parcel.go
> +		return parcel, err
В случае ошибки лушче вернуть чистую структуру пустую, тк в parcerl могут быть битые данные

2024-11-08 08:08 UTC, just-musha commented on main.go
> +	CREATE TABLE IF NOT EXISTS parcels (
Как будто отступа не хватает на строчках 107-112

2024-11-08 08:08 UTC, just-musha commented on parcel.go
> +		return 0, err
Везде где возвращаешь ошибку - можно ещё ее обергнуть чтобы добавить больше контекста - fmt.Errorf("scan failed %w", err). Некритично, но полезно в работе, можешь здесь или в фин задании применить.

https://rollbar.com/blog/golang-wrap-and-unwrap-error/

2024-11-08 08:08 UTC, just-musha commented on parcel_test.go
> +	require.Equal(t, parcel.Client, gotParcel.Client)
Тоже лучше assert для всех проверок

2024-11-08 08:08 UTC, just-musha commented on parcel_test.go
> +	require.Error(t, err)
Можно ещё проверить что это именно нужная ошибка, а не какая-то другая

2024-11-08 20:11 UTC, IlyaOsipenkov commented on parcel_test.go
> +		require.Equal(t, parcelMap[parcel.Number].Client, parcel.Client)
Исправил

2024-11-08 20:11 UTC, IlyaOsipenkov commented on main.go
> +//test
Нет, удалил

2024-11-08 20:12 UTC, IlyaOsipenkov commented on parcel.go
> +type ParcelStore interface {
Благодарю!

2024-11-08 20:12 UTC, IlyaOsipenkov commented on parcel.go
> +	}
Исправил

2024-11-08 20:12 UTC, IlyaOsipenkov commented on parcel.go
> +		return parcel, err
Исправил, не подумал об этом сразу, спасибо

2024-11-08 20:12 UTC, IlyaOsipenkov commented on main.go
> +	CREATE TABLE IF NOT EXISTS parcels (
Сделал форматирование

2024-11-08 20:13 UTC, IlyaOsipenkov commented on parcel.go
> +		return 0, err
Исправил, спасибо за этот комментарий, думаю это важный момент для ерорхендлинга

2024-11-08 20:14 UTC, IlyaOsipenkov commented on parcel_test.go
> +	require.Equal(t, parcel.Client, gotParcel.Client)
Исправил

2024-11-08 20:14 UTC, IlyaOsipenkov commented on parcel_test.go
> +	require.Error(t, err)
Здесь я не совсем понял на какую именно ошибку я должен проверить, добавил свой вариант и подписал комментарием "Like this?"

2024-11-08 20:16 UTC, merged

2024-11-08 20:23 UTC, IlyaOsipenkov commented
@just-musha Добрый вечер! Спасибо за развернутые комментарии, отработал по всем

2024-11-09 10:26 UTC, just-musha reviewed
Супер! Спасибо за доработки (и комментарии, мне важно видеть что было полезно). Принято!

2024-11-09 10:26 UTC, just-musha commented on parcel_test.go
> +	require.True(t, errors.Is(err, sql.ErrNoRows), "expected sql.ErrNoRows error")
Да!